// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3S_0PlcnSfxFVw1Ys1j6gtrWRw0K4JJg',
    appId: '1:863532707394:web:4234755cd7e82277e907db',
    messagingSenderId: '863532707394',
    projectId: 'menthriftshop-98bb2',
    authDomain: 'menthriftshop-98bb2.firebaseapp.com',
    storageBucket: 'menthriftshop-98bb2.appspot.com',
    measurementId: 'G-95FSV17M0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUrVl1_MNwlJSEWD6EsXYzoATOksjGH3w',
    appId: '1:863532707394:android:3a0562ee1562ca77e907db',
    messagingSenderId: '863532707394',
    projectId: 'menthriftshop-98bb2',
    storageBucket: 'menthriftshop-98bb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX34qbzoH0__Xj1yGgtv3nRQXdJ9LPlgo',
    appId: '1:863532707394:ios:e75fb6ad9c6f24d7e907db',
    messagingSenderId: '863532707394',
    projectId: 'menthriftshop-98bb2',
    storageBucket: 'menthriftshop-98bb2.appspot.com',
    iosClientId: '863532707394-br8u8qfaerrbhcte8ghhbur9ha5s8s50.apps.googleusercontent.com',
    iosBundleId: 'com.example.thrift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX34qbzoH0__Xj1yGgtv3nRQXdJ9LPlgo',
    appId: '1:863532707394:ios:e75fb6ad9c6f24d7e907db',
    messagingSenderId: '863532707394',
    projectId: 'menthriftshop-98bb2',
    storageBucket: 'menthriftshop-98bb2.appspot.com',
    iosClientId: '863532707394-br8u8qfaerrbhcte8ghhbur9ha5s8s50.apps.googleusercontent.com',
    iosBundleId: 'com.example.thrift',
  );
}
